apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kagent
  namespace: argocd
spec:
  description: Kagent project for AI agent management
  sourceRepos:
  - 'https://github.com/papagala/argo-kagent.git'  # Update this with your actual repo URL
  - 'oci://ghcr.io/kagent-dev/kmcp/helm'
  destinations:
  - namespace: kagent
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: apps
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: kagent.dev
    kind: '*'
  roles:
  - name: admin
    description: Admin access to kagent project
    policies:
    - p, proj:kagent:admin, applications, *, kagent/*, allow
    - p, proj:kagent:admin, repositories, *, *, allow
    groups:
    - kagent:admin