apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kagent
  source:
    repoURL: https://github.com/papagala/argo-kagent.git
    targetRevision: HEAD
    path: kagent
    helm:
      valueFiles:
        - values.yaml
      # No need to override the API key here - it will use the secret in the kagent namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # For CRD updates
  revisionHistoryLimit: 10