apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: m3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kagent
  source:
    repoURL: https://github.com/papagala/argo-kagent.git
    targetRevision: HEAD
    path: helm-charts/m3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
